url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Zhang Laboratory" # the name of your site, e.g. ACME Corp.
description: "Organic Synthesis for Drug Discovery"
avatar: "/images/zhangcheng_photo.jpg" 
email: "chengzhang@gzhmu.edu.cn"