menu:
  - {name: 'Assay', url: '/research'}
  - {name: 'ChemLib', url: '/chemlib'}
  - {name: 'Team', url: '/people'}
  - {name: 'Publications', url: '/publications'}
  - {name: 'Contact', url: '/contact'}

Assay:
  - {name: 'Organic Synthesis', url: '/assay/organic-synthesis'}
  - {name: 'Flavivirus Inhibitors', url: '/assay/flavivirus-inhibitors'}
  - {name: 'AI for Drug Discovery', url: '/assay/ai'}

ChemLib:
  - {name: 'Chemical Library', url: '/chemlib/library'}

people:
  - {name: 'Wei Yi',       title: "Professor", email: 'yiwei@gzhmu.edu.cn',     image: '/assets/img/People/yiwei.png',         url: 'yi-wei'}
  - {name: 'Junfeng Zhao', title: "Professor", email: 'hello@gzhmu.edu.cn',      image: '/assets/img/People/Junfeng Zhao.jpeg', url: 'junfeng-zhao'}
  - {name: 'Zhixiong Ruan',title: "Professor", email: 'zruan@gzhmu.edu.cn',      image: '/assets/img/People/ruanzhixiong.jpg',  url: 'ruan-zhixiong'}
  - {name: 'Shiying Li',   title: "Professor", email: 'hello@gzhmu.edu.cn',      image: '/assets/img/People/Shiying Li.jpeg',   url: 'shiying-li'}
  - {name: 'Youwei Xu',    title: "Professor", email: 'hello@gzhmu.edu.cn',      image: '/assets/img/People/Youwei Xu.jpeg',    url: 'youwei-xu'}
  - {name: 'Shuimu Lin',   title: "Professor", email: 'hello@gzhmu.edu.cn',      image: '/assets/img/People/shuimu-lin.jpg',    url: 'shuimu-lin'}
  - {name: 'Zhi Zhou',     title: "Professor", email: 'hello@gzhmu.edu.cn',      image: '/assets/img/People/Zhi Zhou.jpeg',     url: 'zhi-zhou'}
  - {name: 'Cheng Zhang',  title: "Professor", email: 'zhangcheng@gzhmu.edu.cn', image: '/assets/img/People/zhangcheng.jpg',    url: 'zhang-cheng'}

publications:
  - {name: 'Microbiology', url: '/publications/microbiology'}
  - {name: 'Organic Chemistry', url: '/publications/organic-chemistry'}
  - {name: 'Pharmacal Chemistry', url: '/publications/pharmacal-chemistry'}

contact:
  - {name: 'Cheng Zhang', title: "Professor", research_interests: "Organic Chemistry, Medicinal Chemistry", email: 'chengzhang@gzhmu.edu.cn', office_location: 'Technology Building Room 828, Xinzao, Panyu District, Guangzhou, 511436', image: '/assets/img/PI3.jpg'}